export const GET_DJMESSAGELIST_REQUEST = "GET_DJMESSAGELIST_REQUEST";
export const GET_DJMESSAGELIST_SUCCESS = "GET_DJMESSAGELIST_SUCCESS";
export const GET_DJMESSAGELIST_FAILURE = "GET_DJMESSAGELIST_FAILURE";

export const THEME_CHANGE = "THEME_CHANGE";

export const DJ_MENU = "DJ_MENU";